Imports System
Imports System.Drawing
Imports System.Windows.Forms
Imports DevExpress.XtraCharts

Namespace CustomAxisLabels
    Partial Public Class Form1
        Inherits Form

        Public Sub New()
            InitializeComponent()
        End Sub

        #Region "#CustomLabels"
        Private Sub Form1_Load(ByVal sender As Object, ByVal e As EventArgs) Handles Me.Load
            ' Cast the chart's diagram to the XYDiagram type, to access its axes.
            Dim diagram As XYDiagram = TryCast(chartControl.Diagram, XYDiagram)
            If diagram Is Nothing Then
                Return
            End If

            Dim axisX As AxisX = diagram.AxisX
            ' Add a custom label to the X-axis.
            axisX.CustomLabels.Add(New CustomAxisLabel(name:= "State of Michigan", value:= "Michigan") With { _
                .TextColor = Color.FromArgb(255, 74, 74, 74), _
                .BackColor = Color.FromArgb(255, 225, 225, 225) _
            })
            ' Make auto-generated and custom labels visible at the same time.
            axisX.LabelVisibilityMode = AxisLabelVisibilityMode.AutoGeneratedAndCustom
        End Sub
        #End Region
    End Class
End Namespace